project_id = "ljzjfupzlabjlzipveal"

[functions.send-smtp-email]
verify_jwt = false

[functions.send-notification]
verify_jwt = false

[functions.send-2fa-code]
verify_jwt = false

[functions.verify-2fa-code]
verify_jwt = false