
-- Add new SMTP config keys (encryption mode + reply-to)
INSERT INTO public.platform_settings (key, value, category, description)
VALUES
  ('smtp_encryption', '"tls"'::jsonb, 'email', 'SMTP encryption mode: tls (STARTTLS, port 587), ssl (implicit, port 465), or none'),
  ('smtp_reply_to', '""'::jsonb, 'email', 'Reply-To address for outgoing emails'),
  ('smtp_enabled', 'true'::jsonb, 'email', 'Master switch for SMTP-based notifications'),
  ('email_2fa_code_ttl_minutes', '10'::jsonb, 'email', 'Minutes that a 2FA email code stays valid')
ON CONFLICT (key) DO NOTHING;

-- 2FA email codes table
CREATE TABLE IF NOT EXISTS public.email_2fa_codes (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  email text NOT NULL,
  code_hash text NOT NULL,
  purpose text NOT NULL DEFAULT 'login',
  expires_at timestamptz NOT NULL,
  consumed_at timestamptz,
  attempts int NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_email_2fa_codes_user ON public.email_2fa_codes(user_id, created_at DESC);
ALTER TABLE public.email_2fa_codes ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "users_select_own_2fa_codes" ON public.email_2fa_codes;
CREATE POLICY "users_select_own_2fa_codes" ON public.email_2fa_codes
  FOR SELECT TO authenticated USING (user_id = auth.uid());

DROP POLICY IF EXISTS "admins_manage_2fa_codes" ON public.email_2fa_codes;
CREATE POLICY "admins_manage_2fa_codes" ON public.email_2fa_codes
  FOR ALL TO authenticated USING (public.is_admin(auth.uid())) WITH CHECK (public.is_admin(auth.uid()));

-- Beautiful HTML email templates for all events
-- Helper: a single shared HTML wrapper baked into each template body for consistency.

-- Universal placeholders available: {{site_name}}, {{site_url}}, {{logo_url}}, {{recipient_name}},
-- {{amount}}, {{currency}}, {{creator_name}}, {{receipt}}, {{date}}, {{event_name}}, {{order_number}},
-- {{ticket_qr}}, {{code}}, {{action_url}}, {{reason}}, {{message}}, {{support_email}}

INSERT INTO public.notification_templates (event_type, channel, subject, body, is_active, placeholders) VALUES
('donation_confirmed', 'email', '💚 Thank you for supporting {{creator_name}}',
'<!DOCTYPE html><html><body style="margin:0;padding:0;background:#f5f7fa;font-family:-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,sans-serif;color:#1f2937;"><table width="100%" cellpadding="0" cellspacing="0" style="background:#f5f7fa;padding:32px 16px;"><tr><td align="center"><table width="600" cellpadding="0" cellspacing="0" style="max-width:600px;background:#ffffff;border-radius:16px;overflow:hidden;box-shadow:0 4px 20px rgba(0,0,0,.06);"><tr><td style="background:linear-gradient(135deg,#e0365b,#ff6a8a);padding:32px;text-align:center;"><div style="font-size:48px;line-height:1;">💚</div><h1 style="margin:12px 0 0;color:#ffffff;font-size:24px;">Donation Received!</h1></td></tr><tr><td style="padding:32px;"><p style="margin:0 0 16px;font-size:16px;">Hi {{recipient_name}},</p><p style="margin:0 0 24px;font-size:16px;line-height:1.6;">Your generous contribution of <strong style="color:#e0365b;">{{currency}} {{amount}}</strong> to <strong>{{creator_name}}</strong> was received successfully.</p><table width="100%" style="background:#f9fafb;border-radius:12px;padding:20px;margin-bottom:24px;"><tr><td style="font-size:14px;color:#6b7280;">Receipt</td><td align="right" style="font-size:14px;font-weight:600;">{{receipt}}</td></tr><tr><td style="font-size:14px;color:#6b7280;padding-top:8px;">Date</td><td align="right" style="font-size:14px;font-weight:600;padding-top:8px;">{{date}}</td></tr></table><p style="margin:0 0 24px;font-size:15px;color:#4b5563;line-height:1.6;">You are turning fans into family — thank you for being part of this tribe. 🙏</p><a href="{{site_url}}" style="display:inline-block;background:#e0365b;color:#fff;text-decoration:none;padding:12px 24px;border-radius:10px;font-weight:600;">Visit {{site_name}}</a></td></tr><tr><td style="background:#f9fafb;padding:20px;text-align:center;font-size:12px;color:#9ca3af;">Need help? Contact us at {{support_email}}<br/>© {{site_name}}</td></tr></table></td></tr></table></body></html>',
true, '["recipient_name","amount","currency","creator_name","receipt","date","site_name","site_url","support_email"]'::jsonb),

('gift_confirmed', 'email', '🎁 Your gift to {{creator_name}} was delivered',
'<!DOCTYPE html><html><body style="margin:0;background:#f5f7fa;font-family:-apple-system,Segoe UI,sans-serif;"><table width="100%" cellpadding="0" cellspacing="0" style="padding:32px 16px;"><tr><td align="center"><table width="600" style="background:#fff;border-radius:16px;overflow:hidden;box-shadow:0 4px 20px rgba(0,0,0,.06);"><tr><td style="background:linear-gradient(135deg,#7c3aed,#e0365b);padding:32px;text-align:center;color:#fff;"><div style="font-size:48px;">🎁</div><h1 style="margin:12px 0 0;font-size:24px;">Gift Delivered</h1></td></tr><tr><td style="padding:32px;color:#1f2937;"><p style="font-size:16px;">Hi {{recipient_name}},</p><p style="font-size:16px;line-height:1.6;">Your <strong>{{currency}} {{amount}}</strong> gift to <strong>{{creator_name}}</strong> just lit up their day. ✨</p><div style="background:#f9fafb;border-radius:12px;padding:20px;margin:20px 0;"><div style="font-size:14px;color:#6b7280;">Receipt: <strong style="color:#1f2937;">{{receipt}}</strong></div><div style="font-size:14px;color:#6b7280;margin-top:6px;">Date: <strong style="color:#1f2937;">{{date}}</strong></div></div><a href="{{site_url}}" style="display:inline-block;background:#7c3aed;color:#fff;padding:12px 24px;border-radius:10px;text-decoration:none;font-weight:600;">Send another gift</a></td></tr><tr><td style="background:#f9fafb;padding:20px;text-align:center;font-size:12px;color:#9ca3af;">© {{site_name}} · {{support_email}}</td></tr></table></td></tr></table></body></html>',
true, '["recipient_name","amount","currency","creator_name","receipt","date","site_name","site_url","support_email"]'::jsonb),

('vote_confirmed', 'email', '🗳️ Vote confirmed for {{creator_name}}',
'<!DOCTYPE html><html><body style="margin:0;background:#f5f7fa;font-family:-apple-system,Segoe UI,sans-serif;"><table width="100%" cellpadding="0" cellspacing="0" style="padding:32px 16px;"><tr><td align="center"><table width="600" style="background:#fff;border-radius:16px;overflow:hidden;box-shadow:0 4px 20px rgba(0,0,0,.06);"><tr><td style="background:linear-gradient(135deg,#f59e0b,#e0365b);padding:32px;text-align:center;color:#fff;"><div style="font-size:48px;">🏆</div><h1 style="margin:12px 0 0;">Your votes are in!</h1></td></tr><tr><td style="padding:32px;"><p>Hi {{recipient_name}},</p><p style="line-height:1.6;">You cast votes worth <strong style="color:#e0365b;">{{currency}} {{amount}}</strong> for <strong>{{creator_name}}</strong>. Receipt: <code>{{receipt}}</code>.</p><p style="line-height:1.6;color:#4b5563;">Watch the leaderboard climb in real time on {{site_name}}.</p><a href="{{site_url}}" style="display:inline-block;background:#e0365b;color:#fff;padding:12px 24px;border-radius:10px;text-decoration:none;font-weight:600;">See standings</a></td></tr><tr><td style="background:#f9fafb;padding:20px;text-align:center;font-size:12px;color:#9ca3af;">© {{site_name}}</td></tr></table></td></tr></table></body></html>',
true, '["recipient_name","amount","currency","creator_name","receipt","site_name","site_url"]'::jsonb),

('ticket_confirmed', 'email', '🎟️ Ticket for {{event_name}}',
'<!DOCTYPE html><html><body style="margin:0;background:#f5f7fa;font-family:-apple-system,Segoe UI,sans-serif;"><table width="100%" cellpadding="0" cellspacing="0" style="padding:32px 16px;"><tr><td align="center"><table width="600" style="background:#fff;border-radius:16px;overflow:hidden;box-shadow:0 4px 20px rgba(0,0,0,.06);"><tr><td style="background:linear-gradient(135deg,#0ea5e9,#7c3aed);padding:32px;text-align:center;color:#fff;"><div style="font-size:48px;">🎟️</div><h1 style="margin:12px 0 0;">You are going!</h1></td></tr><tr><td style="padding:32px;"><p>Hi {{recipient_name}},</p><p style="line-height:1.6;">Your ticket to <strong>{{event_name}}</strong> on <strong>{{date}}</strong> is confirmed.</p><div style="background:#f9fafb;border-radius:12px;padding:20px;text-align:center;margin:20px 0;"><div style="font-family:monospace;font-size:18px;letter-spacing:2px;color:#0ea5e9;">{{ticket_qr}}</div><div style="font-size:12px;color:#6b7280;margin-top:8px;">Show this code at the door</div></div><div style="font-size:14px;color:#6b7280;">Receipt: {{receipt}} · {{currency}} {{amount}}</div></td></tr><tr><td style="background:#f9fafb;padding:20px;text-align:center;font-size:12px;color:#9ca3af;">© {{site_name}}</td></tr></table></td></tr></table></body></html>',
true, '["recipient_name","event_name","date","ticket_qr","receipt","amount","currency","site_name"]'::jsonb),

('order_confirmed', 'email', '📦 Order {{order_number}} confirmed',
'<!DOCTYPE html><html><body style="margin:0;background:#f5f7fa;font-family:-apple-system,Segoe UI,sans-serif;"><table width="100%" cellpadding="0" cellspacing="0" style="padding:32px 16px;"><tr><td align="center"><table width="600" style="background:#fff;border-radius:16px;overflow:hidden;box-shadow:0 4px 20px rgba(0,0,0,.06);"><tr><td style="background:linear-gradient(135deg,#10b981,#0ea5e9);padding:32px;text-align:center;color:#fff;"><div style="font-size:48px;">📦</div><h1 style="margin:12px 0 0;">Order Confirmed</h1></td></tr><tr><td style="padding:32px;"><p>Hi {{recipient_name}},</p><p style="line-height:1.6;">Order <strong>{{order_number}}</strong> for <strong>{{currency}} {{amount}}</strong> has been received.</p><p style="color:#4b5563;line-height:1.6;">{{message}}</p><a href="{{site_url}}/account" style="display:inline-block;background:#10b981;color:#fff;padding:12px 24px;border-radius:10px;text-decoration:none;font-weight:600;">Track order</a></td></tr><tr><td style="background:#f9fafb;padding:20px;text-align:center;font-size:12px;color:#9ca3af;">© {{site_name}}</td></tr></table></td></tr></table></body></html>',
true, '["recipient_name","order_number","amount","currency","site_name","site_url","message"]'::jsonb),

('withdrawal_requested', 'email', '💸 Withdrawal request received',
'<!DOCTYPE html><html><body style="margin:0;background:#f5f7fa;font-family:-apple-system,Segoe UI,sans-serif;"><table width="100%" cellpadding="0" cellspacing="0" style="padding:32px 16px;"><tr><td align="center"><table width="600" style="background:#fff;border-radius:16px;overflow:hidden;box-shadow:0 4px 20px rgba(0,0,0,.06);"><tr><td style="background:linear-gradient(135deg,#f59e0b,#ef4444);padding:32px;text-align:center;color:#fff;"><div style="font-size:48px;">💸</div><h1 style="margin:12px 0 0;">Withdrawal Pending</h1></td></tr><tr><td style="padding:32px;"><p>Hi {{recipient_name}},</p><p style="line-height:1.6;">We received your withdrawal request for <strong>{{currency}} {{amount}}</strong>. Our team is reviewing it now and you will get another email once approved (usually within 24h).</p><div style="background:#fffbeb;border-left:4px solid #f59e0b;padding:14px 16px;border-radius:8px;color:#78350f;font-size:14px;">Reference: <strong>{{receipt}}</strong></div></td></tr><tr><td style="background:#f9fafb;padding:20px;text-align:center;font-size:12px;color:#9ca3af;">© {{site_name}}</td></tr></table></td></tr></table></body></html>',
true, '["recipient_name","amount","currency","receipt","site_name"]'::jsonb),

('withdrawal_approved', 'email', '✅ Withdrawal of {{currency}} {{amount}} approved',
'<!DOCTYPE html><html><body style="margin:0;background:#f5f7fa;font-family:-apple-system,Segoe UI,sans-serif;"><table width="100%" cellpadding="0" cellspacing="0" style="padding:32px 16px;"><tr><td align="center"><table width="600" style="background:#fff;border-radius:16px;overflow:hidden;box-shadow:0 4px 20px rgba(0,0,0,.06);"><tr><td style="background:linear-gradient(135deg,#10b981,#059669);padding:32px;text-align:center;color:#fff;"><div style="font-size:48px;">✅</div><h1 style="margin:12px 0 0;">Funds On The Way</h1></td></tr><tr><td style="padding:32px;"><p>Hi {{recipient_name}},</p><p style="line-height:1.6;">Your withdrawal of <strong style="color:#10b981;">{{currency}} {{amount}}</strong> has been approved and is being disbursed to your registered M-PESA / bank account.</p><div style="background:#ecfdf5;border-radius:10px;padding:16px;color:#065f46;font-size:14px;margin-top:16px;">Reference: <strong>{{receipt}}</strong> · Date: {{date}}</div></td></tr><tr><td style="background:#f9fafb;padding:20px;text-align:center;font-size:12px;color:#9ca3af;">© {{site_name}}</td></tr></table></td></tr></table></body></html>',
true, '["recipient_name","amount","currency","receipt","date","site_name"]'::jsonb),

('withdrawal_rejected', 'email', '⚠️ Withdrawal request needs attention',
'<!DOCTYPE html><html><body style="margin:0;background:#f5f7fa;font-family:-apple-system,Segoe UI,sans-serif;"><table width="100%" cellpadding="0" cellspacing="0" style="padding:32px 16px;"><tr><td align="center"><table width="600" style="background:#fff;border-radius:16px;overflow:hidden;box-shadow:0 4px 20px rgba(0,0,0,.06);"><tr><td style="background:linear-gradient(135deg,#ef4444,#b91c1c);padding:32px;text-align:center;color:#fff;"><div style="font-size:48px;">⚠️</div><h1 style="margin:12px 0 0;">Withdrawal Declined</h1></td></tr><tr><td style="padding:32px;"><p>Hi {{recipient_name}},</p><p style="line-height:1.6;">Your withdrawal request for <strong>{{currency}} {{amount}}</strong> could not be processed.</p><div style="background:#fef2f2;border-left:4px solid #ef4444;padding:14px 16px;border-radius:8px;color:#991b1b;font-size:14px;">Reason: {{reason}}</div><p style="line-height:1.6;margin-top:16px;">Reach out to {{support_email}} and we will sort it out fast.</p></td></tr><tr><td style="background:#f9fafb;padding:20px;text-align:center;font-size:12px;color:#9ca3af;">© {{site_name}}</td></tr></table></td></tr></table></body></html>',
true, '["recipient_name","amount","currency","reason","support_email","site_name"]'::jsonb),

('creator_approved', 'email', '🎉 Welcome to the {{site_name}} creator family',
'<!DOCTYPE html><html><body style="margin:0;background:#f5f7fa;font-family:-apple-system,Segoe UI,sans-serif;"><table width="100%" cellpadding="0" cellspacing="0" style="padding:32px 16px;"><tr><td align="center"><table width="600" style="background:#fff;border-radius:16px;overflow:hidden;box-shadow:0 4px 20px rgba(0,0,0,.06);"><tr><td style="background:linear-gradient(135deg,#e0365b,#7c3aed);padding:36px;text-align:center;color:#fff;"><div style="font-size:54px;">🎉</div><h1 style="margin:12px 0 0;font-size:26px;">You are approved!</h1></td></tr><tr><td style="padding:32px;"><p style="font-size:16px;">Hi {{recipient_name}},</p><p style="line-height:1.6;font-size:15px;">Your creator profile is live on {{site_name}}. Fans can now donate, gift, vote, and buy your merch.</p><a href="{{action_url}}" style="display:inline-block;background:#e0365b;color:#fff;padding:14px 28px;border-radius:12px;text-decoration:none;font-weight:600;margin-top:8px;">Open Creator Dashboard</a><p style="margin-top:24px;color:#6b7280;font-size:14px;">Pro tip: install {{site_name}} to your home screen for instant access to earnings, notifications, and M-PESA payouts.</p></td></tr><tr><td style="background:#f9fafb;padding:20px;text-align:center;font-size:12px;color:#9ca3af;">© {{site_name}}</td></tr></table></td></tr></table></body></html>',
true, '["recipient_name","action_url","site_name"]'::jsonb),

('two_factor_code', 'email', '🔐 Your {{site_name}} verification code',
'<!DOCTYPE html><html><body style="margin:0;background:#f5f7fa;font-family:-apple-system,Segoe UI,sans-serif;"><table width="100%" cellpadding="0" cellspacing="0" style="padding:32px 16px;"><tr><td align="center"><table width="500" style="background:#fff;border-radius:16px;overflow:hidden;box-shadow:0 4px 20px rgba(0,0,0,.06);"><tr><td style="background:linear-gradient(135deg,#1f2937,#111827);padding:32px;text-align:center;color:#fff;"><div style="font-size:42px;">🔐</div><h1 style="margin:12px 0 0;font-size:22px;">Verify it is you</h1></td></tr><tr><td style="padding:32px;text-align:center;"><p style="margin:0 0 8px;color:#4b5563;">Use this code to continue signing in:</p><div style="font-size:36px;font-weight:700;letter-spacing:10px;color:#1f2937;background:#f3f4f6;border-radius:12px;padding:20px;margin:16px 0;">{{code}}</div><p style="font-size:13px;color:#9ca3af;margin:0;">This code expires in 10 minutes. If you did not request it, ignore this email and consider changing your password.</p></td></tr><tr><td style="background:#f9fafb;padding:18px;text-align:center;font-size:12px;color:#9ca3af;">© {{site_name}} · Stay safe</td></tr></table></td></tr></table></body></html>',
true, '["code","site_name"]'::jsonb),

('campaign_contribution', 'email', '🚀 New backer for "{{event_name}}"',
'<!DOCTYPE html><html><body style="margin:0;background:#f5f7fa;font-family:-apple-system,Segoe UI,sans-serif;"><table width="100%" cellpadding="0" cellspacing="0" style="padding:32px 16px;"><tr><td align="center"><table width="600" style="background:#fff;border-radius:16px;overflow:hidden;box-shadow:0 4px 20px rgba(0,0,0,.06);"><tr><td style="background:linear-gradient(135deg,#0ea5e9,#10b981);padding:32px;text-align:center;color:#fff;"><div style="font-size:48px;">🚀</div><h1 style="margin:12px 0 0;">Campaign Boost!</h1></td></tr><tr><td style="padding:32px;"><p>Hi {{recipient_name}},</p><p style="line-height:1.6;">A new contribution of <strong style="color:#10b981;">{{currency}} {{amount}}</strong> just landed on your campaign <strong>{{event_name}}</strong>.</p><a href="{{action_url}}" style="display:inline-block;background:#0ea5e9;color:#fff;padding:12px 24px;border-radius:10px;text-decoration:none;font-weight:600;">View campaign</a></td></tr><tr><td style="background:#f9fafb;padding:20px;text-align:center;font-size:12px;color:#9ca3af;">© {{site_name}}</td></tr></table></td></tr></table></body></html>',
true, '["recipient_name","amount","currency","event_name","action_url","site_name"]'::jsonb)
ON CONFLICT DO NOTHING;
